### PR TITLE
duqtools init now outputs commented yaml file

### PR DESCRIPTION
**Pull request by v1kko**

### CODE REVIEW

**Comment by v1kko** [comment]
@stefsmeets  this adds comments to the duqtools init command, which is nice, but I wanted to see if you agree on the custom `setup.cfg pydantic-yaml` dependency

**Comment by v1kko** [comment]
Also there might be a better way to add the descriptions, although the `Field` way seems to work fine

**Review by stefsmeets — APPROVED** [review]
Thanks @v1kko , this is really cool! And it works well! Can you change the existing `pyyaml` imports to use `ruamel.yaml` instead?

Another thing (can be added later) is that it would be great if the comments could start on the line above, and wrap to let's say 80 characters so that we can have longer descriptions.

**Comment by v1kko** [comment]
> Thanks @v1kko , this is really cool! And it works well! Can you change the existing `pyyaml` imports to use `ruamel.yaml` instead?
> 
> Another thing (can be added later) is that it would be great if the comments could start on the line above, and wrap to let's say 80 characters so that we can have longer descriptions.

Agree, I'll make a new issue out of this

**Pull request merged**
