### PR TITLE
Add manager to couple settings between jetto.jset, jetto.in

### LINKED ISSUE #220: Allow jetto tool parameters to be edited
- Create a tool to update some values in multiple places 
  - Create a mapping file which is easily updateable as new mappings might be added later on

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR adds a layer around the jetto.jset / jetto.in wrappers that maps a single common values to multiple destination fields across multiple config files.

The settings are defined in a yaml file.

Closes #220

### CODE REVIEW

**Comment by stefsmeets** [comment]
Hi @v1kko Could you have a look at this PR and let me know what you think?

**Review by v1kko — APPROVED** [review]
A very nice job! The inner system is very complex (took me a while to figure out how it exactly works), but the resulting JettoSettings manager should do exactly what we need! 

Perhaps it can use a test for the settings manager as well? (we can also write that later)

**Comment by stefsmeets** [comment]
Thanks! Do you have any ideas how we could reduce the complexity?

**Comment by v1kko** [comment]
could we make a dict based access structure for the JettoSettingsManager? and delay the checking/setting of the setters/getters until these calls? 

I think the confusing part is the triple nested `__new__` function which adds attribute functions to the class.

But I do like that then the settable options show up as attribute, so it is fine as is I would think. Maybe some explanation about what the `__new__` function does would help.

**Comment by stefsmeets** [comment]
I agree that the triple nesting is tricky. Dict-like access to these objects does not feel natural to me considering the side-effects. This feels better as properties.

I will implement the tests and then we can simplify the logic later if there is time.

**Comment by fcasson** [comment]
I think this is a reinvention of the main functionality we have in the jetto-pythontools API.   Have you looked at it at all?

https://jintrac.gitlab.io/jetto-pythontools/

**Comment by stefsmeets** [comment]
> I think this is a reinvention of the main functionality we have in the jetto-pythontools API. Have you looked at it at all?
> 
> https://jintrac.gitlab.io/jetto-pythontools/

Hi @fcasson, thanks for the suggestion. I must admit that I'm still not entirely sure what it is that `jetto-pythontools` does. We have looked at it at the start of this project, but decided that the functionality we needed was trivial enough not to have to depend on an external package for it.

Also, as far as I'm aware, the code is not released on pypi or elsewhere, which makes it difficult to integrate with our package.

**Comment by fcasson** [comment]
If we want to build common shared tooling and a logical package structure then I think depending on an external package will be inevitable 

If you need it to be on pypi, then let's put it there (although personally I don't know how to do this).  It is open on gitlab.com https://gitlab.com/jintrac/jetto-pythontools/.  This is just a mirror of a primary at JET (where the issues are tracked) but we can accept merge requests on gitlab.com if that is easiest for you.

**Comment by stefsmeets** [comment]
Uploading to pypi itself is not difficult. The tricky part is beating the package in the right shape, making sure all the data files are included, and tweaking your setup.py / setup.cfg so that it installs correctly. This is something we can help with.

There are plenty of tutorials on the internet, I usually start with this one: https://packaging.python.org/en/latest/tutorials/packaging-projects/.

For this project, there is a [github action](https://github.com/CarbonCollective/fusion-dUQtools/blob/main/.github/workflows/publish.yaml) that automatically triggers the upload to pypi whenever a release is created. So you essentially set it up once and then forget about it. Gitlab (or your favourite CI) has similar capabilities.

I don't think we have access to the JET repos, but we'll figure something out.

**Comment by fcasson** [comment]
If JET repo access is an issue I am happy to invert things and make [gitlab.com](http://gitlab.com/) the primary, or at least take merge requests from there.

**Comment by v1kko** [comment]
Some extra information for future reference (For how we can adress this issue): 

In `duqtools` we have implemented a `System` interface. this `System` provides a way to work with various backends ,`jetto` being one of them (the only one currently besides a `dummy` system). If we are to implement this coupling via `jetto-pythontools` we could leverage this and create a new `System` for this (and make it the default if desired). In that way the tool could both be neatly integrated into the `jetto` tooling environment, while retaining flexibility regarding choice of backend.

**Pull request merged**
